const projects = [
  {
    title: 'Recipe Finder',
    link: 'https://www.youtube.com/watch?v=FlYsB-SBM1s&ab_channel=EddieXiao',
    image: require('../../assets/Project/recipe.png'),
    dateRange: '2022 – 2023',
    summary: 'An Android app for tailored recipe suggestions.',
    bullets: [
      'Utilized ingredient-based search to suggest recipes.',
      'Enhanced meal planning with user-friendly design.',
      'Improved user retention with a clean interface.',
    ],
    tags: [
      { name: 'Android Studio' },
      { name: 'Java' },
      { name: 'Figma' },
    ],
  },
  {
    title: 'Machine Learning Beginner Project',
    link: 'https://github.com/eddieX-2021/MLbeginnerProject',
    image: require('../../assets/Project/mlbeginner.png'),
    dateRange: '2023 – 2024',
    summary: 'Built foundational skills in machine learning.',
    bullets: [
      'Predicted rainfall using Scikit-learn and Pandas.',
      'Visualized results using Matplotlib for clarity.',
      'Gained insights into weather pattern prediction.',
    ],
    tags: [
      { name: 'Python' },
      { name: 'Machine Learning' },
      { name: 'Feature Engineering' },
    ],
  },
  {
    title: 'Eggs By The Dozen',
    link: 'https://github.com/3amBEANS/EggsByTheDozen',
    image: require('../../assets/Project/egg.png'),
    dateRange: '2023 – 2024',
    summary: 'Tool to detect parasites in egg images.',
    bullets: [
      'Collaborated with local farmers for dataset creation.',
      'Applied machine learning techniques for image analysis.',
      'Reduced inspection time and improved accuracy.',
    ],
    tags: [
      { name: 'Computer Vision' },
      { name: 'PyTorch' },
      { name: 'Python' },
    ],
  },
  {
    title: 'To-Do List App',
    link: 'https://github.com/eddieX-2021/TodoList',
    image: require('../../assets/Project/todo.png'),
    dateRange: '2023 – 2024',
    summary: 'Flask-based task management app.',
    bullets: [
      'Built a responsive frontend with HTML and JavaScript.',
      'Implemented efficient task creation and editing.',
      'Integrated Flask backend for data management.',
    ],
    tags: [
      { name: 'Flask' },
      { name: 'HTML' },
      { name: 'JavaScript' },
      { name: 'Node.js' },
    ],
  },
  {
    title: 'Restaurant Recommendation',
    link: 'https://github.com/eddieX-2021/restaurant-recommandation',
    image: require('../../assets/Project/restu.png'),
    dateRange: '2024 – 2025',
    summary: 'Personalized restaurant recommendation system.',
    bullets: [
      'Used ML methods to analyze user preferences.',
      'Integrated Google Maps API for location-based results.',
      'Improved user satisfaction through tailored suggestions.',
    ],
    tags: [
      { name: 'Machine Learning' },
      { name: 'Google Maps' },
      { name: 'Python' },
    ],
  },
  {
    title: 'Course Review Website',
    link: 'https://github.com/orgs/uva-cs3140-fa24/teams/hw6-pym4ns-uyh9nu-mgn3uh',
    image: require('../../assets/Project/course.png'),
    dateRange: '2024 – 2025',
    summary: 'Java-based platform for course reviews.',
    bullets: [
      'Developed SQL backend for reliable data storage.',
      'Enabled users to leave ratings and detailed reviews.',
      'Provided an intuitive user interface for navigation.',
    ],
    tags: [
      { name: 'Java' },
      { name: 'SQL' },
      { name: 'Web UI' },
    ],
  },
  {
    title: 'Personal Portfolio',
    link: 'https://github.com/eddieX-2021/portfolio',
    image: require('../../assets/Project/portfolio.png'),
    dateRange: '2024 – Present',
    summary: 'Showcased projects and skills on a personal website.',
    bullets: [
      'Built with React for a dynamic and responsive layout.',
      'Integrated EmailJS for contact form functionality.',
      'Highlighted skills and projects effectively.',
    ],
    tags: [
      { name: 'React' },
      { name: 'EmailJS' },
      { name: 'Frontend' },
    ],
  },
  {
    title: 'Early-Career Salary Prediction & ROI Analysis',
    link: 'https://github.com/huygnguyen04/Early-Career-Salary-Prediction-and-ROI-Analysis',
    image: require('../../assets/Project/ROI.png'),
    dateRange: '2023',
    summary: 'Research on salary ROI across colleges & states.',
    bullets: [
      'Built Random Forest regression model for salary predictions.',
      'Performed ROI calculations to rank colleges by financial value.',
      'Visualized insights using ggplot2 for data-driven decisions.',
    ],
    tags: [
      { name: 'R' },
      { name: 'Feature Engineering' },
      { name: 'Machine Learning' },
    ],
  },
  {
    title: 'Linear Regression App',
    link: 'https://huynguyen1211.shinyapps.io/APMA3150-ExtraCreditProject/',
    image: require('../../assets/Project/shiny.png'),
    dateRange: '2023',
    summary: 'Interactive Shiny app demonstrating linear regression.',
    bullets: [
      'Enabled CSV uploads and variable selection.',
      'Displayed slope, intercept, and R² metrics alongside plot.',
    ],
    tags: [
      { name: 'Shiny' },
      { name: 'R' },
      { name: 'Machine Learning' },
    ],
  },
  {
    title: 'Predict Next Word',
    link: 'https://github.com/eddieX-2021/PredictNextWord',
    image: require('../../assets/Project/Predit.png'),
    dateRange: '2025',
    summary: 'LSTM-based next-word predictor on Shakespeare’s text.',
    bullets: [
      'Built LSTM network and tokenizer pipeline.',
      'Deployed via Streamlit for interactive predictions.',
      'Implemented early stopping and full ML lifecycle.',
    ],
    tags: [
      { name: 'LSTM' },
      { name: 'Deep Learning' },
      { name: 'Streamlit' },
      { name: 'Conda' },
      { name: 'Feature Engineering' },
    ],
  },
  {
    title: 'Anime Review Sentiment Analysis',
    link: 'https://github.com/eddieX-2021/SimpleRNNReview',
    image: require('../../assets/Project/Simple.png'),
    dateRange: '2025',
    summary: 'Simple RNN for anime review sentiment.',
    bullets: [
      'Demonstrated full NLP pipeline in Streamlit.',
      'Explored RNN limitations and future improvements.',
    ],
    tags: [
      { name: 'Simple RNN' },
      { name: 'Deep Learning' },
      { name: 'Streamlit' },
      { name: 'Conda' },
      { name: 'Feature Engineering' },
    ],
  },
  {
    title: 'UCLA Graduate Admission Predictor',
    link: 'https://github.com/eddieX-2021/mlGradAdmission',
    image: require('../../assets/Project/UCLA.png'),
    dateRange: '2025',
    summary: 'Flask app predicting UCLA admission chances.',
    bullets: [
      'Built ML pipeline with custom logging & exceptions.',
      'Real-time local predictions with user inputs.',
    ],
    tags: [
      { name: 'Machine Learning' },
      { name: 'Conda' },
      { name: 'Feature Engineering' },
    ],
  },
  {
    title: 'Heart Disease Prediction (ANN)',
    link: 'https://github.com/eddieX-2021/HeartDiseaseWithANN',
    image: require('../../assets/Project/Heart.png'),
    dateRange: '2025',
    summary: 'TensorFlow ANN for heart disease risk.',
    bullets: [
      'End-to-end Streamlit app with data preprocessing.',
      'Integrated scikit-learn & Keras into real-time UI.',
    ],
    tags: [
      { name: 'Artificial Neural Networks' },
      { name: 'Deep Learning' },
      { name: 'Streamlit' },
      { name: 'Feature Engineering' },
    ],
  },
  {
    title: 'Gear Share',
    link: 'https://github.com/eddieX-2021/GearShare',
    image: require('../../assets/Project/sum.webp'),
    dateRange: '2025',
    summary: 'Outdoor Gear Sharing Platform.',
    bullets: [
      'Built a Django web app for sharing, borrowing, and managing items in a community.',
      'Integrated AWS S3 for secure image and media storage.',
    ],
    tags: [
      { name: 'Django' },
      { name: 'AWS' },
      { name: 'Bootstrap' },
      { name: 'JavaScript' },
    ],
  },
  {
    title: 'AI Stock Prediction',
    link: 'https://stock-prediction-app-two.vercel.app/',
    image: require('../../assets/Project/stock.png'),
    dateRange: '2025 – Present',
    summary: 'Four-model ensemble for stock forecasting.',
    bullets: [
      '90% accuracy with linear baseline; 75% with advanced models.',
      'Automated ingest, NewsAPI/Reddit sentiment, CI/CD on Render/Vercel.',
    ],
    tags: [
      { name: 'Machine Learning' },
      { name: 'Deep Learning' },
      { name: 'Next.js' },
      { name: 'FastAPI' },
    ],
  },
  {
    title: 'ShapeShift (Health Platform)',
    link: 'https://shape-shift-vert.vercel.app/',
    image: require('../../assets/Project/ShapeShift.png'),
    dateRange: '2025 – Present',
    summary: 'AI-driven weight/muscle management with dashboards.',
    bullets: [
      'Personalized workouts via Google Gemini & food-recog model.',
      'Recharts + Tailwind/ShadCN dashboards for progress tracking.',
    ],
    tags: [
      { name: 'Google Gemini' },
      { name: 'JWT' },
      { name: 'Next.js' },
      { name: 'Node.js' },
      { name: 'MongoDB' },
      { name: 'Shadcn' },
    ],
  },
  {
    title: 'Haven Explorer',
    link: 'https://github.com/eddieX-2021/HavenExplorer',
    image: require('../../assets/Project/haven.png'),
    dateRange: '2025 – Present',
    summary: 'Real estate comparison & budgeting app.',
    bullets: [
      'Saved homes, compared life costs & risks.',
      'AWS ECS/EC2 + S3 for containerized, scalable services.',
    ],
    tags: [
      { name: 'Google Gemini' },
      { name: 'JWT' },
      { name: 'Next.js' },
      { name: 'Node.js' },
      { name: 'PostgreSQL' },
      { name: 'Shadcn' },
    ],
  },
];

export default projects;
